version: "3.8"

volumes: 
  esdata:
    driver: local

services:
  product:
    build:
      context: ./services/product
      dockerfile: Dockerfile
    image: product
    ports:
      - "8085:8085"
    expose:
      - 8085
    container_name: product
  
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    image: database
    ports:
      - "8086:8086"
    expose:
      - 8086
    container_name: database
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9200
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch
